#include "arPrimitiveValue.h"
#include "arInstructions.h"

arPrimitiveValue arPrimitiveValue_i8(arInt8 value)
{
	arPrimitiveValue c = { 0, ARLANG_PRIMITIVE_I8 };
	c.i8 = value;
	return c;
}

arPrimitiveValue arPrimitiveValue_ui8(arUint8 value)
{
	arPrimitiveValue c = { 0, ARLANG_PRIMITIVE_UI8 };
	c.ui8 = value;
	return c;
}

arPrimitiveValue arPrimitiveValue_i86(arInt16 value)
{
	arPrimitiveValue c = { 0, ARLANG_PRIMITIVE_I16 };
	c.i16 = value;
	return c;
}

arPrimitiveValue arPrimitiveValue_ui86(arUint16 value)
{
	arPrimitiveValue c = { 0, ARLANG_PRIMITIVE_UI16 };
	c.ui16 = value;
	return c;
}

arPrimitiveValue arPrimitiveValue_i32(arInt32 value)
{
	arPrimitiveValue c = { 0, ARLANG_PRIMITIVE_I32 };
	c.i32 = value;
	return c;
}

arPrimitiveValue arPrimitiveValue_ui32(arUint32 value)
{
	arPrimitiveValue c = { 0, ARLANG_PRIMITIVE_UI32 };
	c.ui32 = value;
	return c;
}

arPrimitiveValue arPrimitiveValue_i64(arInt64 value)
{
	arPrimitiveValue c = { 0, ARLANG_PRIMITIVE_I64 };
	c.i64 = value;
	return c;
}

arPrimitiveValue arPrimitiveValue_ui64(arUint64 value)
{
	arPrimitiveValue c = { 0, ARLANG_PRIMITIVE_UI64 };
	c.ui64 = value;
	return c;
}

arPrimitiveValue arPrimitiveValue_f32(arFloat32 value)
{
	arPrimitiveValue c = { 0, ARLANG_PRIMITIVE_F32 };
	c.f32 = value;
	return c;
}

arPrimitiveValue arPrimitiveValue_f64(arFloat64 value)
{
	arPrimitiveValue c = { 0, ARLANG_PRIMITIVE_F64 };
	c.f64 = value;
	return c;
}

arPrimitiveValue arPrimitiveValue_ptr(arByte* value)
{
	arPrimitiveValue c = { 0, ARLANG_PRIMITIVE_PTR };
	c.ptr = value;
	return c;
}

BOOL arPrimitiveValue_not_implemented(arPrimitiveValue* lhs, const arPrimitiveValue* rhs)
{
	ASSERT_NOT_IMPLEMENTED();
	return FALSE;
}

BOOL arPrimitiveValue_not_allowed(arPrimitiveValue* lhs, const arPrimitiveValue* rhs)
{
	return FALSE;
}

arPrimitive arPrimitiveValue_datatype(arInt32 lhs, arInt32 rhs)
{
	static const arPrimitive types[ARLANG_PRIMITIVE_COUNT][ARLANG_PRIMITIVE_COUNT] = {
		// UNKNOWN
		{ 
			0 
		},
		// BOOL
		{ 
			0, ARLANG_PRIMITIVE_BOOL
		},
		// INT8
		{ 
			0, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32,
			ARLANG_PRIMITIVE_UI32, ARLANG_PRIMITIVE_I64, ARLANG_PRIMITIVE_UI64, ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_PTR
		},
		// UINT8
		{
			0, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32,
			ARLANG_PRIMITIVE_UI32, ARLANG_PRIMITIVE_I64, ARLANG_PRIMITIVE_UI64, ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_PTR
		},
		// INT16
		{
			0, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32,
			ARLANG_PRIMITIVE_UI32, ARLANG_PRIMITIVE_I64, ARLANG_PRIMITIVE_UI64, ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_PTR
		},
		// UINT16
		{
			0, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32,
			ARLANG_PRIMITIVE_UI32, ARLANG_PRIMITIVE_I64, ARLANG_PRIMITIVE_UI64, ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_PTR
		},
		// INT32
		{
			0, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32, ARLANG_PRIMITIVE_I32,
			ARLANG_PRIMITIVE_UI32, ARLANG_PRIMITIVE_I64, ARLANG_PRIMITIVE_UI64, ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_PTR
		},
		// UINT32
		{
			0, ARLANG_PRIMITIVE_UI32, ARLANG_PRIMITIVE_UI32, ARLANG_PRIMITIVE_UI32, ARLANG_PRIMITIVE_UI32, ARLANG_PRIMITIVE_UI32, ARLANG_PRIMITIVE_UI32,
			ARLANG_PRIMITIVE_UI32, ARLANG_PRIMITIVE_I64, ARLANG_PRIMITIVE_UI64, ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_PTR
		},
		// INT64
		{
			0, ARLANG_PRIMITIVE_I64, ARLANG_PRIMITIVE_I64, ARLANG_PRIMITIVE_I64, ARLANG_PRIMITIVE_I64, ARLANG_PRIMITIVE_I64, ARLANG_PRIMITIVE_I64,
			ARLANG_PRIMITIVE_I64, ARLANG_PRIMITIVE_I64, ARLANG_PRIMITIVE_UI64, ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_PTR
		},
		// UINT64
		{
			0, ARLANG_PRIMITIVE_UI64, ARLANG_PRIMITIVE_UI64, ARLANG_PRIMITIVE_UI64, ARLANG_PRIMITIVE_UI64, ARLANG_PRIMITIVE_UI64, ARLANG_PRIMITIVE_UI64,
			ARLANG_PRIMITIVE_UI64, ARLANG_PRIMITIVE_UI64, ARLANG_PRIMITIVE_UI64, ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_PTR
		},
		// FLOAT32
		{
			0, ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F32,
			ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F32, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_PTR
		},
		// FLOAT64
		{
			0, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_F64,
			ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_F64, ARLANG_PRIMITIVE_PTR
		},
		// PTR
		{
			0, ARLANG_PRIMITIVE_PTR, ARLANG_PRIMITIVE_PTR, ARLANG_PRIMITIVE_PTR, ARLANG_PRIMITIVE_PTR, ARLANG_PRIMITIVE_PTR, ARLANG_PRIMITIVE_PTR,
			ARLANG_PRIMITIVE_PTR, ARLANG_PRIMITIVE_PTR, ARLANG_PRIMITIVE_PTR, 0, 0, ARLANG_PRIMITIVE_PTR
		}
	};

	if (lhs <= ARLANG_PRIMITIVE_UNKNOWN || lhs >= ARLANG_PRIMITIVE_COUNT)
		return 0;
	if (rhs <= ARLANG_PRIMITIVE_UNKNOWN || rhs  >= ARLANG_PRIMITIVE_COUNT)
		return 0;
	return types[lhs][rhs];
}
